name = "cf-minesweeper"
main = "src/optimized.js"
compatibility_date = "2025-06-20"


[[d1_databases]]
binding = "DB"
database_name = "cf-minesweeper"
database_id = "4bf517b3-8dd9-46ea-830c-d5ad9541a8bd"

[env.production]
name = "cf-minesweeper"
